/** @module fake_data */

/**
 * Array of players with stats info.
 * @type {object[]}
 */
export const fake_players = [
    {
        "number": 14,
        "name": "Andy Dalton",
        "position": "Quarterback",
        "stats": "Passing: 1,856 YDS",
        "image": "https://images.generated.photos/-K9iBY4oOkLsqQfoTA1R8X0EKvR_BCbMXk0KNX4EIIs/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0NzY1MjkuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 7,
        "name": "Ben DiNucci",
        "position": "Quarterback",
        "stats": "Passing: 856 YDS",
        "image": "https://images.generated.photos/EUa6Hmnt6682dl03Q5FPIeMqLnS833rfzOJaJXlYxqI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTk3OTFfMDU1/Nzg5OF8wMzgzMzIw/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 3,
        "name": "Garrett Gilbert",
        "position": "Quarterback",
        "stats": "Passing: 758 YDS",
        "image": "https://images.generated.photos/eGoWRgqxtahGFDAD81-l8CNxdz1oe-huz3CQ7m3v0VI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzNDA0NDlfMDgz/MDY1Nl8wMTk4NTI4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",

    },
    {
        "number": 34,
        "name": "Rico Dowdle",
        "position": "Running back",
        "stats": "1,368 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 21,
        "name": "Ezekiel Elliott",
        "position": "Running back",
        "stats": "1,842 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 20,
        "name": "Tony Pollard",
        "position": "Running back",
        "stats": "1,623 YDS",
        "image": "https://images.generated.photos/cb3jAo-GBziFLxs85KJGt7a8bJdhz4sSy76PYAXkeg4/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA1ODU4MDBfMDMy/NjY2OF8wODEwNTA2/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 85,
        "name": "Noah Brown",
        "position": "Wide receiver",
        "stats": "666 YDS",
        "image": "https://images.generated.photos/LLiy3FypH5A1suda78U82t_Kcn9AlJwZt1g3w1p5DwE/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODc0NjlfMDUy/MDc0NF8wNzc3NzQ5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 19,
        "name": "Amari Cooper",
        "position": "Wide receiver",
        "stats": "256 YDS",
        "image": "https://images.generated.photos/dW84LNLE4Kzp73NTTnL68U--dYuq8CCzD-dGTs76U38/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNjE1NjZfMDEz/NDM1NF8wMTg5MjI0/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 13,
        "name": "Michael Gallup",
        "position": "Wide receiver",
        "stats": "13 YDS",
        "image": "https://images.generated.photos/erudOopARQnXWNaLqkIPRLLMLAVBr8m70aFC_dtYu1Y/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODA5MTVfMDkx/MzIzN18wNDQxMTk4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",

    },
    {
        "number": 88,
        "name": "CeeDee Lamb",
        "position": "Wide receiver",
        "stats": "25 YDS",
        "image": "https://images.generated.photos/WFV4nHHq5ZaBb1rdmFL5WEZTOanckWHEfkmDA1fOVfw/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTYzNzNfMDI4/Nzc2N18wNzYxNDY3/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 17,
        "name": "Malik Turner",
        "position": "Wide receiver",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 11,
        "name": "Cedrick Wilson Jr.",
        "position": "Wide receiver",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 80,
        "name": "Blake Bell",
        "position": "Tight end",
        "image": "https://images.generated.photos/eGoWRgqxtahGFDAD81-l8CNxdz1oe-huz3CQ7m3v0VI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzNDA0NDlfMDgz/MDY1Nl8wMTk4NTI4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 84,
        "name": "Sean McKeon",
        "position": "Tight end",
        "image": "https://images.generated.photos/EUa6Hmnt6682dl03Q5FPIeMqLnS833rfzOJaJXlYxqI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTk3OTFfMDU1/Nzg5OF8wMzgzMzIw/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 86,
        "name": "Dalton Schultz",
        "position": "Tight end",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/-K9iBY4oOkLsqQfoTA1R8X0EKvR_BCbMXk0KNX4EIIs/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0NzY1MjkuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 63,
        "name": "Tyler Biadasz C",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/cb3jAo-GBziFLxs85KJGt7a8bJdhz4sSy76PYAXkeg4/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA1ODU4MDBfMDMy/NjY2OF8wODEwNTA2/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 69,
        "name": "Brandon Knight T/G",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/LLiy3FypH5A1suda78U82t_Kcn9AlJwZt1g3w1p5DwE/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODc0NjlfMDUy/MDc0NF8wNzc3NzQ5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 70,
        "name": "Zack Martin G",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/dW84LNLE4Kzp73NTTnL68U--dYuq8CCzD-dGTs76U38/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNjE1NjZfMDEz/NDM1NF8wMTg5MjI0/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 66,
        "name": "Connor McGovern G",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/erudOopARQnXWNaLqkIPRLLMLAVBr8m70aFC_dtYu1Y/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODA5MTVfMDkx/MzIzN18wNDQxMTk4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 64,
        "name": "Greg Senat T",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/WFV4nHHq5ZaBb1rdmFL5WEZTOanckWHEfkmDA1fOVfw/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTYzNzNfMDI4/Nzc2N18wNzYxNDY3/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 78,
        "name": "Terence Steele T",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 52,
        "name": "Connor Williams G",
        "position": "Offensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 56,
        "name": "Bradlee Anae DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/eGoWRgqxtahGFDAD81-l8CNxdz1oe-huz3CQ7m3v0VI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzNDA0NDlfMDgz/MDY1Nl8wMTk4NTI4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 92,
        "name": "Dorance Armstrong DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/EUa6Hmnt6682dl03Q5FPIeMqLnS833rfzOJaJXlYxqI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTk3OTFfMDU1/Nzg5OF8wMzgzMzIw/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 98,
        "name": "Tyrone Crawford DT/DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/-K9iBY4oOkLsqQfoTA1R8X0EKvR_BCbMXk0KNX4EIIs/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0NzY1MjkuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 96,
        "name": "Neville Gallimore DT",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/cb3jAo-GBziFLxs85KJGt7a8bJdhz4sSy76PYAXkeg4/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA1ODU4MDBfMDMy/NjY2OF8wODEwNTA2/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 94,
        "name": "Randy Gregory DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/LLiy3FypH5A1suda78U82t_Kcn9AlJwZt1g3w1p5DwE/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODc0NjlfMDUy/MDc0NF8wNzc3NzQ5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 97,
        "name": "Everson Griffen DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/dW84LNLE4Kzp73NTTnL68U--dYuq8CCzD-dGTs76U38/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNjE1NjZfMDEz/NDM1NF8wMTg5MjI0/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 79,
        "name": "Justin Hamilton DT",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/erudOopARQnXWNaLqkIPRLLMLAVBr8m70aFC_dtYu1Y/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODA5MTVfMDkx/MzIzN18wNDQxMTk4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 90,
        "name": "DeMarcus Lawrence DE",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/WFV4nHHq5ZaBb1rdmFL5WEZTOanckWHEfkmDA1fOVfw/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTYzNzNfMDI4/Nzc2N18wNzYxNDY3/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 95,
        "name": "Dontari Poe DT",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 58,
        "name": "Aldon Smith DE/OLB",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 99,
        "name": "Antwaun Woods DT",
        "position": "Defensive lineman",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/eGoWRgqxtahGFDAD81-l8CNxdz1oe-huz3CQ7m3v0VI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzNDA0NDlfMDgz/MDY1Nl8wMTk4NTI4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 57,
        "name": "Luke Gifford MLB/OLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/EUa6Hmnt6682dl03Q5FPIeMqLnS833rfzOJaJXlYxqI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTk3OTFfMDU1/Nzg5OF8wMzgzMzIw/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 59,
        "name": "Justin March OLB/MLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/-K9iBY4oOkLsqQfoTA1R8X0EKvR_BCbMXk0KNX4EIIs/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0NzY1MjkuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 54,
        "name": "Jaylon Smith OLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/cb3jAo-GBziFLxs85KJGt7a8bJdhz4sSy76PYAXkeg4/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA1ODU4MDBfMDMy/NjY2OF8wODEwNTA2/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 53,
        "name": "Rashad Smith MLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/LLiy3FypH5A1suda78U82t_Kcn9AlJwZt1g3w1p5DwE/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODc0NjlfMDUy/MDc0NF8wNzc3NzQ5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 48,
        "name": "Joe Thomas OLB/MLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/dW84LNLE4Kzp73NTTnL68U--dYuq8CCzD-dGTs76U38/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNjE1NjZfMDEz/NDM1NF8wMTg5MjI0/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 55,
        "name": "Leighton Vander Esch MLB",
        "position": "Linebacker",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/erudOopARQnXWNaLqkIPRLLMLAVBr8m70aFC_dtYu1Y/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODA5MTVfMDkx/MzIzN18wNDQxMTk4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 30,
        "name": "Anthony Brown CB",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/WFV4nHHq5ZaBb1rdmFL5WEZTOanckWHEfkmDA1fOVfw/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTYzNzNfMDI4/Nzc2N18wNzYxNDY3/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 27,
        "name": "Trevon Diggs CB",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 29,
        "name": "C. J. Goodwin CB",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 26,
        "name": "Jourdan Lewis CB",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/eGoWRgqxtahGFDAD81-l8CNxdz1oe-huz3CQ7m3v0VI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzNDA0NDlfMDgz/MDY1Nl8wMTk4NTI4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 40,
        "name": "Steven Parker SS/FS",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/EUa6Hmnt6682dl03Q5FPIeMqLnS833rfzOJaJXlYxqI/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTk3OTFfMDU1/Nzg5OF8wMzgzMzIw/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 41,
        "name": "Reggie Robinson FS/CB",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/-K9iBY4oOkLsqQfoTA1R8X0EKvR_BCbMXk0KNX4EIIs/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0NzY1MjkuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 23,
        "name": "Darian Thompson SS/FS",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/cb3jAo-GBziFLxs85KJGt7a8bJdhz4sSy76PYAXkeg4/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA1ODU4MDBfMDMy/NjY2OF8wODEwNTA2/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 37,
        "name": "Donovan Wilson SS/FS",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/LLiy3FypH5A1suda78U82t_Kcn9AlJwZt1g3w1p5DwE/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODc0NjlfMDUy/MDc0NF8wNzc3NzQ5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 25,
        "name": "Xavier Woods FS",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/dW84LNLE4Kzp73NTTnL68U--dYuq8CCzD-dGTs76U38/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAyNjE1NjZfMDEz/NDM1NF8wMTg5MjI0/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 28,
        "name": "Daryl Worley CB/S",
        "position": "Defensive back",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/erudOopARQnXWNaLqkIPRLLMLAVBr8m70aFC_dtYu1Y/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAzODA5MTVfMDkx/MzIzN18wNDQxMTk4/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 6,
        "name": "Chris Jones P",
        "position": "Special team",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/WFV4nHHq5ZaBb1rdmFL5WEZTOanckWHEfkmDA1fOVfw/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxNTYzNzNfMDI4/Nzc2N18wNzYxNDY3/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 91,
        "name": "L. P. Ladouceur LS",
        "position": "Special team",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/PEBx5b8_iPHU_nJpJbh3geUN8cBFglHVAAR9NktzXsk/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzAxODI1NzlfMDgx/MTA0OV8wNDQzOTM5/LmpwZw.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    },
    {
        "number": 2,
        "name": "Greg Zuerlein K",
        "position": "Special team",
        "stats": "551 YDS",
        "image": "https://images.generated.photos/fd8kkioB4vLw_5MGwQXdDt9Q7Ley2_Ia8Cu390zaNVM/rs:fit:128:128/Z3M6Ly9nZW5lcmF0/ZWQtcGhvdG9zL3Yz/XzA0Nzg2ODEuanBn.jpg",
        "showing_stats": false,
        "points": 0,
        "speed": 0,
        "price": "$0.00",
    }
]
